<?php
$summary = is_array($snapshot['summary'] ?? null) ? $snapshot['summary'] : [];
$customers = is_array($snapshot['recentCustomers'] ?? null) ? $snapshot['recentCustomers'] : [];
$todayPayments = is_array($snapshot['todayPayments'] ?? null) ? $snapshot['todayPayments'] : [];
$trend = is_array($snapshot['collectionTrend'] ?? null) ? $snapshot['collectionTrend'] : [];
$money = static fn(float|int $v): string => '৳' . number_format((float) $v, 0);
$number = static fn(float|int $v): string => number_format((float) $v);
$csrfToken = htmlspecialchars((string) ($csrfToken ?? $csrf ?? ''), ENT_QUOTES, 'UTF-8');
$profileInitial = strtoupper(substr((string) ($role ?? 'U'), 0, 1));
$maxTrend = 0.0;
foreach ($trend as $point) $maxTrend = max($maxTrend, (float) ($point['amount'] ?? 0));
?>
<!doctype html><html lang="en" data-lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><link rel="stylesheet" href="/assets/css/app.css?v=8"><link rel="stylesheet" href="/assets/css/dashboard.css?v=20"><title>ISPLUKA — Dashboard</title></head><body class="dashboard-page"><div class="app-shell">
<header class="app-header dashboard-header"><div class="container header-inner"><button class="menu-toggle" type="button" data-menu-toggle aria-label="Open navigation" aria-expanded="false">Menu</button><a class="brand" href="/">ISPLUKA</a><div class="header-tools dashboard-header-actions"><label class="global-search"><input type="search" data-search placeholder="Search customer, phone or code…" autocomplete="off"></label><div class="language-switch" role="group" aria-label="Language"><button type="button" data-language="en" class="language-btn active" aria-pressed="true">EN</button><button type="button" data-language="bn" class="language-btn" aria-pressed="false">বাংলা</button></div><a href="/customers" class="profile-button dashboard-profile-button" aria-label="Profile" title="Profile"><?=$profileInitial?></a><form method="post" action="/logout" class="logout-form dashboard-logout-form"><input type="hidden" name="_csrf" value="<?=$csrfToken?>"><button type="submit" class="logout-button dashboard-logout-button">Logout</button></form></div></div></header>
<aside class="sidebar" data-sidebar><nav class="nav dashboard-nav"><div class="nav-brand-mini"><div><strong>ISPLUKA</strong><small>ISP ERP</small></div></div><a class="active" href="/">Dashboard</a><div class="nav-section">Customers &amp; Billing</div><a href="/customers">Customers</a><a href="/customers/create">Add Customer</a><a href="/collection">Collection</a><a href="/reports/collection">Collection Report</a><div class="nav-section">Network</div><a href="/networking/mikrotik/routers">MikroTik Routers</a><a href="/networking/customer">Customer Networking</a><a href="/networking/mikrotik/enforcement-audit">Enforcement Audit</a><a href="/networking/hotspot">Hotspot</a><a href="/networking/olt">OLT</a><div class="nav-section">Management</div><a href="/subscription">Subscription</a><form method="post" action="/logout" class="sidebar-logout-form"><input type="hidden" name="_csrf" value="<?=$csrfToken?>"><button type="submit">Logout</button></form></nav></aside>
<main class="main main-with-sidebar dashboard-main"><div class="container dashboard-container">
<section class="dashboard-simple-head"><h1>Dashboard</h1><p class="simple-muted">Operational overview for <?=htmlspecialchars((string)($tenantName ?? 'Your ISP'), ENT_QUOTES, 'UTF-8')?>.</p></section>
<section class="dashboard-block"><div class="simple-section-title"><h2>Overview</h2></div><div class="dashboard-stat-grid"><article class="stat-card"><span>Total Customers</span><strong><?=$number($summary['customers'] ?? 0)?></strong></article><article class="stat-card stat-active"><span>Active Services</span><strong><?=$number($summary['active_services'] ?? 0)?></strong></article><article class="stat-card stat-warning"><span>Suspended Services</span><strong><?=$number($summary['suspended_services'] ?? 0)?></strong></article><article class="stat-card stat-danger"><span>Overdue Invoices</span><strong><?=$number($summary['overdue_invoices'] ?? 0)?></strong></article><article class="stat-card"><span>Outstanding</span><strong><?=$money($summary['outstanding'] ?? 0)?></strong></article><article class="stat-card stat-active"><span>Today's Collection</span><strong><?=$money($summary['today_collected'] ?? 0)?></strong></article><article class="stat-card"><span>Monthly Collection</span><strong><?=$money($summary['monthly_collected'] ?? 0)?></strong></article><article class="stat-card"><span>New Customers Today</span><strong><?=$number($summary['new_customers_today'] ?? 0)?></strong></article></div></section>
<section class="dashboard-block"><div class="simple-section-title"><h2>Network Health</h2></div><div class="dashboard-network-grid"><article class="network-card"><span>Total MikroTik Routers</span><strong><?=$number($summary['routers_total'] ?? 0)?></strong></article><article class="network-card online"><span>Online Routers</span><strong><?=$number($summary['routers_online'] ?? 0)?></strong></article><article class="network-card offline"><span>Offline Routers</span><strong><?=$number($summary['routers_offline'] ?? 0)?></strong></article><a class="network-card network-link" href="/networking/mikrotik/enforcement-audit"><span>Network Audit</span><strong>Open</strong></a></div></section>
<section class="dashboard-block"><div class="simple-section-title"><h2>Collection Overview</h2><a class="secondary-action" href="/reports/collection">Full Report</a></div><div class="simple-panel collection-trend-panel"><div class="collection-trend" aria-label="Six-month collection trend"><?php foreach ($trend as $point): $amount=(float)($point['amount']??0); $height=$maxTrend>0?max(4,($amount/$maxTrend)*100):4; ?><div class="trend-column"><div class="trend-value"><?=$money($amount)?></div><div class="trend-bar" style="height:<?=number_format($height,2,'.','')?>%" title="<?=htmlspecialchars((string)($point['label']??''),ENT_QUOTES,'UTF-8')?>: <?=$money($amount)?>"></div><small><?=htmlspecialchars((string)($point['label']??''),ENT_QUOTES,'UTF-8')?></small></div><?php endforeach; ?><?php if ($trend===[]): ?><div class="simple-empty">No collection history available.</div><?php endif; ?></div></div></section>
<section class="dashboard-block"><div class="simple-section-title"><h2>Recent Collections</h2><span><?=count($todayPayments)?></span></div><div class="simple-panel"><div class="simple-list"><?php foreach ($todayPayments as $payment): ?><div class="simple-list-row"><span><strong><?=htmlspecialchars((string)($payment['customer_name']??''),ENT_QUOTES,'UTF-8')?></strong><small><?=htmlspecialchars((string)($payment['customer_code']??''),ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars((string)($payment['method']??''),ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars((string)($payment['reference']??''),ENT_QUOTES,'UTF-8')?></small></span><b><?=$money($payment['amount']??0)?></b></div><?php endforeach; ?><?php if ($todayPayments===[]): ?><div class="simple-empty">No bill collection recorded today.</div><?php endif; ?></div></div></section>
<section class="dashboard-block"><div class="simple-section-title"><h2>Recent Customers</h2><span><?=count($customers)?></span></div><div class="simple-panel"><div class="simple-list"><?php foreach ($customers as $customer): ?><a href="/networking/customer?customer_id=<?=rawurlencode((string)($customer['id']??''))?>" class="simple-list-row"><span><strong><?=htmlspecialchars((string)($customer['name']??''),ENT_QUOTES,'UTF-8')?></strong><small><?=htmlspecialchars((string)($customer['customer_code']??''),ENT_QUOTES,'UTF-8')?> · <?=htmlspecialchars((string)($customer['phone']??''),ENT_QUOTES,'UTF-8')?></small></span><b><?=htmlspecialchars((string)($customer['status']??''),ENT_QUOTES,'UTF-8')?></b></a><?php endforeach; ?><?php if ($customers===[]): ?><div class="simple-empty">No customers added this month.</div><?php endif; ?></div></div></section>
<section class="dashboard-block"><div class="simple-section-title"><h2>Quick Actions</h2></div><div class="dashboard-quick-grid dashboard-quick-grid-2x2"><a href="/customers/create" class="quick-card primary dashboard-quick-card"><div><strong>Add Customer</strong><small>Create a new subscriber</small></div></a><a href="/collection" class="quick-card primary dashboard-quick-card"><div><strong>Collection</strong><small>Collect customer payment</small></div></a><a href="/networking/mikrotik/routers" class="quick-card primary dashboard-quick-card"><div><strong>MikroTik Routers</strong><small>Manage and test routers</small></div></a><a href="/networking/customer" class="quick-card primary dashboard-quick-card"><div><strong>Customer Networking</strong><small>Live PPPoE and usage</small></div></a></div></section>
</div></main></div><script src="/assets/js/app.js?v=8"></script><script src="/assets/js/global-ui.js?v=3"></script><script src="/assets/js/dashboard-i18n.js?v=2"></script></body></html>
