<?php

declare(strict_types=1);

namespace Ispluka\Services;

use Ispluka\Core\Network\MikrotikClientInterface;
use Ispluka\Core\Security\SecretBox;
use Ispluka\Repositories\RouterRepository;
use InvalidArgumentException;
use RuntimeException;

final class RouterService
{
    private const API_PORTS=[8728,56983];
    private const SSH_PORTS=[8787,2288,22];
    public function __construct(private readonly RouterRepository $routers,private readonly SecretBox $secrets,private readonly MikrotikClientInterface $client){}
    public function list(int $tenantId):array{return $this->routers->list($tenantId);}
    public function create(int $tenantId,array $data):int{$name=trim((string)($data['name']??''));$code=trim((string)($data['code']??''));$host=trim((string)($data['host']??''));$username=trim((string)($data['username']??''));$password=(string)($data['password']??'');$method=strtolower(trim((string)($data['connection_method']??'api')));if($tenantId<=0||$name===''||$code===''||$host===''||$username===''||$password==='')throw new InvalidArgumentException('Router name, code, host, username and password are required.');$ports=$this->validatePorts($method,$data['api_port']??null,$data['ssh_port']??null);return $this->routers->create($tenantId,['name'=>$name,'code'=>$code,'host'=>$host,'connection_method'=>$method,'api_port'=>$ports['api_port'],'api_ssl_port'=>null,'ssh_port'=>$ports['ssh_port'],'username'=>$username,'encrypted_password'=>$this->secrets->encrypt($password),'verify_ssl'=>(bool)($data['verify_ssl']??true),'status'=>'unknown','metadata'=>$data['metadata']??[]]);}
    public function update(int $tenantId,int $routerId,array $data):void{$router=$this->routers->find($tenantId,$routerId);if($router===null)throw new RuntimeException('Router not found.');$name=trim((string)($data['name']??''));$code=trim((string)($data['code']??''));$host=trim((string)($data['host']??''));$username=trim((string)($data['username']??''));$method=strtolower(trim((string)($data['connection_method']??($router['connection_method']??'api'))));if($name===''||$code===''||$host===''||$username==='')throw new InvalidArgumentException('Router name, code, host and username are required.');$ports=$this->validatePorts($method,$data['api_port']??$router['api_port']??null,$data['ssh_port']??$router['ssh_port']??null);$verifySsl=array_key_exists('verify_ssl',$data)?(bool)$data['verify_ssl']:(bool)($router['verify_ssl']??true);$payload=['name'=>$name,'code'=>$code,'host'=>$host,'connection_method'=>$method,'api_port'=>$ports['api_port'],'api_ssl_port'=>null,'ssh_port'=>$ports['ssh_port'],'username'=>$username,'verify_ssl'=>$verifySsl,'status'=>'unknown','last_error'=>null];$password=(string)($data['password']??'');if($password!=='')$payload['encrypted_password']=$this->secrets->encrypt($password);$this->routers->update($tenantId,$routerId,$payload);}
    public function delete(int $tenantId,int $routerId):void{if($routerId<=0||!$this->routers->find($tenantId,$routerId))throw new RuntimeException('Router not found.');$this->routers->delete($tenantId,$routerId);}
    public function status(int $tenantId,int $routerId):array{return $this->testConnection($tenantId,$routerId);}
    public function testConnection(int $tenantId,int $routerId):array{if($routerId<=0)throw new InvalidArgumentException('Router ID is required.');$router=$tenantId>0?$this->routers->find($tenantId,$routerId):$this->routers->findAny($routerId);if($router===null)throw new RuntimeException('Router not found.');$actualTenantId=(int)$router['tenant_id'];$method=strtolower((string)($router['connection_method']??'api'));$targetPort=$method==='ssh'?(int)($router['ssh_port']??22):(int)($router['api_port']??8728);try{$this->client->connect($this->routerConfig($router));$identity=$this->client->command('/system/identity/print');$resource=$this->client->command('/system/resource/print');$health=$this->normalizeHealth($resource[0]??[]);$this->routers->markConnection($actualTenantId,$routerId,true);return ['ok'=>true,'status'=>'online','connection_method'=>$method,'host'=>(string)$router['host'],'port'=>$targetPort,'identity'=>$identity[0]['name']??null,'health'=>$health];}catch(\Throwable $e){$message=trim($e->getMessage())!==''?$e->getMessage():'Unknown MikroTik connection error.';$this->routers->markConnection($actualTenantId,$routerId,false,$message);return ['ok'=>false,'status'=>'offline','connection_method'=>$method,'host'=>(string)$router['host'],'port'=>$targetPort,'error'=>$message];}finally{try{$this->client->disconnect();}catch(\Throwable $ignore){}}}
    public function activePppoe(int $tenantId,int $routerId,?string $username=null):array{$router=$this->routers->find($tenantId,$routerId);if($router===null)throw new RuntimeException('Router not found.');$username=trim((string)$username);try{$this->client->connect($this->routerConfig($router));$active=$this->client->command('/ppp/active/print',$username!==''?['?name'=>$username]:[]);$secrets=$this->client->command('/ppp/secret/print',['=.proplist'=>'name']);$this->routers->markConnection($tenantId,$routerId,true);$rows=array_map(static function(array $row):array{return ['id'=>$row['.id']??null,'name'=>$row['name']??null,'service'=>$row['service']??'pppoe','address'=>$row['address']??null,'caller_id'=>$row['caller-id']??$row['caller_id']??null,'uptime'=>$row['uptime']??null,'encoding'=>$row['encoding']??null,'session_id'=>$row['session-id']??$row['session_id']??null];},$active);return ['sessions'=>$rows,'total_customers'=>count($secrets),'active_customers'=>count($rows)];}catch(\Throwable $e){$this->routers->markConnection($tenantId,$routerId,false,$e->getMessage());throw new RuntimeException('Unable to read active PPPoE sessions.',0,$e);}finally{try{$this->client->disconnect();}catch(\Throwable $ignore){}}}
    public function disconnectPppoe(int $tenantId,int $routerId,string $username):array{$username=trim($username);if($username==='')throw new InvalidArgumentException('PPPoE username is required.');$router=$this->routers->find($tenantId,$routerId);if($router===null)throw new RuntimeException('Router not found.');try{$this->client->connect($this->routerConfig($router));$rows=$this->client->command('/ppp/active/print',['?name'=>$username]);if($rows===[])throw new RuntimeException('No active PPPoE session found for this username.');$removed=0;foreach($rows as $row){if(!empty($row['.id'])){$this->client->command('/ppp/active/remove',['.id'=>$row['.id']]);$removed++;}}$this->routers->markConnection($tenantId,$routerId,true);return ['ok'=>true,'username'=>$username,'removed'=>$removed];}catch(\Throwable $e){$this->routers->markConnection($tenantId,$routerId,false,$e->getMessage());throw new RuntimeException('Unable to disconnect PPPoE session.',0,$e);}finally{try{$this->client->disconnect();}catch(\Throwable $ignore){}}}
    public function provisionPppoe(int $tenantId,int $routerId,string $username,string $password,string $profile):void{$this->provisionUser($tenantId,$routerId,'/ppp/secret/print','/ppp/secret/add','/ppp/secret/set',$username,['name'=>$username,'password'=>$password,'service'=>'pppoe','profile'=>$profile]);}
    public function suspendPppoe(int $tenantId,int $routerId,string $username):void{$this->toggleUser($tenantId,$routerId,'/ppp/secret/print','/ppp/secret/disable',$username);}
    public function restorePppoe(int $tenantId,int $routerId,string $username):void{$this->toggleUser($tenantId,$routerId,'/ppp/secret/print','/ppp/secret/enable',$username);}
    public function provisionHotspot(int $tenantId,int $routerId,string $username,string $password,string $profile):void{$this->provisionUser($tenantId,$routerId,'/ip/hotspot/user/print','/ip/hotspot/user/add','/ip/hotspot/user/set',$username,['name'=>$username,'password'=>$password,'profile'=>$profile]);}
    public function suspendHotspot(int $tenantId,int $routerId,string $username):void{$this->toggleUser($tenantId,$routerId,'/ip/hotspot/user/print','/ip/hotspot/user/disable',$username);}
    public function restoreHotspot(int $tenantId,int $routerId,string $username):void{$this->toggleUser($tenantId,$routerId,'/ip/hotspot/user/print','/ip/hotspot/user/enable',$username);}
    private function provisionUser(int $tenantId,int $routerId,string $findCommand,string $addCommand,string $setCommand,string $username,array $data):void{$router=$this->routers->find($tenantId,$routerId);if($router===null)throw new RuntimeException('Router not found.');try{$this->client->connect($this->routerConfig($router));$rows=$this->client->command($findCommand,['?name'=>$username]);if(!empty($rows[0]['.id']))$this->client->command($setCommand,['.id'=>$rows[0]['.id']]+$data);else $this->client->command($addCommand,$data);$this->routers->markConnection($tenantId,$routerId,true);}catch(\Throwable $e){$this->routers->markConnection($tenantId,$routerId,false,$e->getMessage());throw new RuntimeException('Router provisioning failed.',0,$e);}finally{try{$this->client->disconnect();}catch(\Throwable $ignore){}}}
    private function toggleUser(int $tenantId,int $routerId,string $findCommand,string $actionCommand,string $username):void{$router=$this->routers->find($tenantId,$routerId);if($router===null)throw new RuntimeException('Router not found.');try{$this->client->connect($this->routerConfig($router));$rows=$this->client->command($findCommand,['?name'=>$username]);if(empty($rows[0]['.id']))throw new RuntimeException('Service account not found.');$this->client->command($actionCommand,['.id'=>$rows[0]['.id']]);$this->routers->markConnection($tenantId,$routerId,true);}catch(\Throwable $e){$this->routers->markConnection($tenantId,$routerId,false,$e->getMessage());throw new RuntimeException('Router service state change failed.',0,$e);}finally{try{$this->client->disconnect();}catch(\Throwable $ignore){}}}
    private function validatePorts(string $method,mixed $api,mixed $ssh):array{if(!in_array($method,['api','ssh'],true))throw new InvalidArgumentException('Connection method must be API or SSH.');$apiPort=(int)($api!==null&&$api!==''?$api:8728);$sshPort=(int)($ssh!==null&&$ssh!==''?$ssh:22);if($method==='api'&&!in_array($apiPort,self::API_PORTS,true))throw new InvalidArgumentException('RouterOS API port must be TCP 8728 or TCP 56983.');if($method==='ssh'&&!in_array($sshPort,self::SSH_PORTS,true))throw new InvalidArgumentException('RouterOS SSH port must be TCP 8787, TCP 2288 or TCP 22.');return ['api_port'=>$apiPort,'ssh_port'=>$sshPort];}
    private function routerConfig(array $router):array{$method=strtolower((string)($router['connection_method']??'api'));if($method==='ssh')return ['host'=>(string)$router['host'],'connection_method'=>'ssh','ssh_port'=>(int)($router['ssh_port']??22),'username'=>(string)$router['username'],'password'=>$this->secrets->decrypt((string)$router['encrypted_password'])];$port=(int)($router['api_port']??8728);if(!in_array($port,self::API_PORTS,true))throw new RuntimeException('Invalid RouterOS API port. Allowed ports: 8728 or 56983.');return ['host'=>(string)$router['host'],'connection_method'=>'api','api_port'=>$port,'username'=>(string)$router['username'],'password'=>$this->secrets->decrypt((string)$router['encrypted_password']),'verify_ssl'=>(bool)($router['verify_ssl']??true),'api_ssl'=>false];}
    private function normalizeHealth(array $resource):array{$number=static function(mixed $value):?float{if($value===null||$value==='')return null;if(is_int($value)||is_float($value))return(float)$value;$value=trim((string)$value);if($value==='')return null;if(preg_match('/^(-?\d+(?:\.\d+)?)\s*%$/',$value,$m))return(float)$m[1];if(preg_match('/^(-?\d+(?:\.\d+)?)\s*(KiB|MiB|GiB|TiB|KB|MB|GB|TB)$/i',$value,$m)){return(float)$m[1]*match(strtoupper($m[2])){ 'KIB'=>1024,'MIB'=>1024**2,'GIB'=>1024**3,'TIB'=>1024**4,'KB'=>1000,'MB'=>1000**2,'GB'=>1000**3,'TB'=>1000**4};}return is_numeric($value)?(float)$value:null;};$memoryTotal=$number($resource['total-memory']??$resource['total_memory']??null);$memoryFree=$number($resource['free-memory']??$resource['free_memory']??null);$memoryUsed=($memoryTotal!==null&&$memoryFree!==null)?max(0,$memoryTotal-$memoryFree):null;$memoryPct=($memoryTotal!==null&&$memoryTotal>0&&$memoryUsed!==null)?round(($memoryUsed/$memoryTotal)*100,1):null;return ['uptime'=>(string)($resource['uptime']??''),'version'=>(string)($resource['version']??''),'board_name'=>(string)($resource['board-name']??$resource['board_name']??''),'architecture'=>(string)($resource['architecture-name']??$resource['architecture_name']??''),'cpu_load'=>$number($resource['cpu-load']??$resource['cpu_load']??null),'total_memory'=>$memoryTotal,'free_memory'=>$memoryFree,'used_memory'=>$memoryUsed,'memory_used_percent'=>$memoryPct];}
}
