<?php

declare(strict_types=1);
namespace Ispluka\Core\Hotspot;
use Ispluka\Core\Security\SecretBox;
use PDO;use InvalidArgumentException;use RuntimeException;
final class HotspotCrudService{
 public function __construct(private readonly PDO $pdo,private readonly HotspotValidityService $validity,private readonly SecretBox $secrets){}
 public function createProfile(int$t,array$d):int{$this->tenant($t);$n=trim((string)($d['name']??''));$c=trim((string)($d['code']??''));$v=ValidityDuration::parse((string)($d['validity']??''));if($n===''||$c==='')throw new InvalidArgumentException('Profile name and code are required.');$s=$this->pdo->prepare("INSERT INTO hotspot_profiles(tenant_id,name,code,validity_expression,validity_seconds,activation_mode,rate_limit,data_limit_bytes,session_limit_seconds,shared_users,status) VALUES(:t,:n,:c,:v,:s,'first_login',:r,:d,:sl,:su,'active') RETURNING id");$s->execute([':t'=>$t,':n'=>$n,':c'=>$c,':v'=>$v->normalized,':s'=>$v->seconds,':r'=>$d['rate_limit']??null,':d'=>$d['data_limit_bytes']??null,':sl'=>$d['session_limit_seconds']??null,':su'=>max(1,(int)($d['shared_users']??1))]);return(int)$s->fetchColumn();}
 public function updateProfile(int$t,int$i,array$d):void{$this->tenant($t);$f=[];$p=[':t'=>$t,':i'=>$i];foreach(['name','code','rate_limit','data_limit_bytes','session_limit_seconds','shared_users','status']as$k)if(array_key_exists($k,$d)){$f[]="$k=:{$k}";$p[":{$k}"]=$k==='shared_users'?max(1,(int)$d[$k]):$d[$k];}if(array_key_exists('validity',$d)){$v=ValidityDuration::parse((string)$d['validity']);$f[]='validity_expression=:ve';$f[]='validity_seconds=:vs';$p[':ve']=$v->normalized;$p[':vs']=$v->seconds;}if(!$f)throw new InvalidArgumentException('No profile fields supplied.');$s=$this->pdo->prepare('UPDATE hotspot_profiles SET '.implode(',',$f).',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=:t AND id=:i');$s->execute($p);if($s->rowCount()!==1)throw new RuntimeException('Hotspot profile not found.');}
 public function deleteProfile(int$t,int$i):void{$this->tenant($t);$c=$this->pdo->prepare('SELECT COUNT(*) FROM hotspot_users WHERE tenant_id=:t AND profile_id=:i');$c->execute([':t'=>$t,':i'=>$i]);if((int)$c->fetchColumn()>0)throw new RuntimeException('Cannot delete a profile that has Hotspot users.');$s=$this->pdo->prepare('DELETE FROM hotspot_profiles WHERE tenant_id=:t AND id=:i');$s->execute([':t'=>$t,':i'=>$i]);if($s->rowCount()!==1)throw new RuntimeException('Hotspot profile not found.');}
 public function createUser(int$t,array$d):int{$this->tenant($t);$u=trim((string)($d['username']??''));$pw=(string)($d['password']??'');$p=(int)($d['profile_id']??0);$r=(int)($d['router_id']??0);if($u===''||$pw===''||$p<1)throw new InvalidArgumentException('Username, password and profile are required.');$q=$this->pdo->prepare("SELECT id FROM hotspot_profiles WHERE tenant_id=:t AND id=:i AND status='active'");$q->execute([':t'=>$t,':i'=>$p]);if(!$q->fetchColumn())throw new RuntimeException('Hotspot profile not found.');$q=$this->pdo->prepare('SELECT 1 FROM hotspot_users WHERE tenant_id=:t AND username=:u');$q->execute([':t'=>$t,':u'=>$u]);if($q->fetchColumn())throw new RuntimeException('Hotspot username already exists.');$s=$this->pdo->prepare("INSERT INTO hotspot_users(tenant_id,router_id,profile_id,username,password_ciphertext,status,mac_address,activated_at,expires_at,created_at,updated_at) VALUES(:t,:r,:p,:u,:pw,'unused',:mac,NULL,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id");$s->execute([':t'=>$t,':r'=>$r>0?$r:null,':p'=>$p,':u'=>$u,':pw'=>$this->secrets->encrypt($pw),':mac'=>$d['mac_address']??null]);return(int)$s->fetchColumn();}
 public function updateUser(int$t,int$i,array$d):void{$this->tenant($t);$f=[];$p=[':t'=>$t,':i'=>$i];foreach(['username','mac_address','router_id']as$k)if(array_key_exists($k,$d)){$f[]="$k=:{$k}";$p[":{$k}"]=$k==='router_id'?((int)$d[$k]>0?(int)$d[$k]:null):trim((string)$d[$k]);}if(array_key_exists('password',$d)&&((string)$d['password'])!==''){$f[]='password_ciphertext=:pw';$p[':pw']=$this->secrets->encrypt((string)$d['password']);}if(array_key_exists('profile_id',$d)){$f[]='profile_id=:p';$p[':p']=(int)$d['profile_id'];}if(!$f)throw new InvalidArgumentException('No Hotspot user fields supplied.');$s=$this->pdo->prepare('UPDATE hotspot_users SET '.implode(',',$f).',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=:t AND id=:i AND status<>\'expired\'');$s->execute($p);if($s->rowCount()!==1)throw new RuntimeException('Hotspot user not found or expired.');}
 public function setUserStatus(int$t,int$i,string$s):void{if(!in_array($s,['disabled','unused'],true))throw new InvalidArgumentException('Invalid Hotspot user status.');$sql=$s==='unused'?"UPDATE hotspot_users SET status=CASE WHEN activated_at IS NULL THEN 'unused' ELSE CASE WHEN expires_at>CURRENT_TIMESTAMP THEN 'active' ELSE 'expired' END END,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=:t AND id=:i AND status<>'expired'":"UPDATE hotspot_users SET status='disabled',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=:t AND id=:i AND status<>'expired'";$q=$this->pdo->prepare($sql);$q->execute([':t'=>$t,':i'=>$i]);if($q->rowCount()!==1)throw new RuntimeException('Hotspot user not found or expired.');}
 public function activateUser(int$t,int$i):array{return$this->validity->activate($t,$i);}public function expireDue(int$t):int{return$this->validity->expireDue($t);}private function tenant(int$t):void{if($t<1)throw new RuntimeException('Invalid tenant context.');}}
