<?php

declare(strict_types=1);
namespace Ispluka\Core\Automation;
use Ispluka\Core\Database\Database;
use Ispluka\Core\Network\MikrotikAutomationService;
final class NetworkJobWorker {
 public function __construct(private readonly Database $db,private readonly MikrotikAutomationService $network) {}
 public function run(int $limit=20):array { $pdo=$this->db->pdo();$pdo->beginTransaction();try{$s=$pdo->prepare("SELECT * FROM network_jobs WHERE status='pending' AND available_at<=CURRENT_TIMESTAMP ORDER BY id FOR UPDATE SKIP LOCKED LIMIT :l");$s->bindValue(':l',min(max($limit,1),100),\PDO::PARAM_INT);$s->execute();$jobs=$s->fetchAll();if($jobs){$ids=array_column($jobs,'id');$u=$pdo->prepare("UPDATE network_jobs SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=ANY(:ids::bigint[])");$u->execute([':ids'=>'{'.implode(',',$ids).'}']);}$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}$done=0;$failed=0;foreach($jobs as $j){try{$result=match($j['action']){'provision'=>$this->network->provision((int)$j['tenant_id'],(int)$j['service_id']),'suspend'=>$this->network->suspend((int)$j['tenant_id'],(int)$j['service_id']),'restore'=>$this->network->restore((int)$j['tenant_id'],(int)$j['service_id']),'enable'=>$this->network->enable((int)$j['tenant_id'],(int)$j['service_id']),'disable'=>$this->network->disable((int)$j['tenant_id'],(int)$j['service_id']),default=>throw new \RuntimeException('Unknown network action')};if(in_array($j['action'],['suspend','restore'],true)){$status=$j['action']==='suspend'?'suspended':'active';$reason=$j['action']==='suspend'?'Billing overdue':null;$u=$pdo->prepare('UPDATE customer_services SET status=:status,suspended_at=:at,suspended_reason=:reason,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=:t AND id=:id');$u->execute([':status'=>$status,':at'=>$j['action']==='suspend'?'CURRENT_TIMESTAMP':null,':reason'=>$reason,':t'=>$j['tenant_id'],':id'=>$j['service_id']]);} $pdo->prepare("UPDATE network_jobs SET status='completed',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='processing'")->execute([':id'=>$j['id']]);$done++;}catch(\Throwable $e){$attempt=(int)$j['attempts'];$delay=min(3600,30*(2**min($attempt,6)));$status=$attempt>=(int)$j['max_attempts']?'failed':'pending';$pdo->prepare("UPDATE network_jobs SET status=:s,last_error=:e,available_at=CURRENT_TIMESTAMP + (:d || ' seconds')::interval,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='processing'")->execute([':s'=>$status,':e'=>substr($e->getMessage(),0,1000),':d'=>$delay,':id'=>$j['id']]);$failed++;}}return['completed'=>$done,'failed_or_requeued'=>$failed];}
}
