<?php

declare(strict_types=1);
namespace Ispluka\Controllers;
use Ispluka\Core\Http\Request;
use Ispluka\Core\Http\Response;
use Ispluka\Core\Network\PppoeEnforcementAuditQuery;
use PDO;
final class MikrotikEnforcementAuditController
{
 public function __construct(private readonly PDO $pdo){}
 private function tenant(Request $r):int{return (int)($r->attribute('tenant_id')??0);}
 public function audit(Request $r):Response{$t=$this->tenant($r);$status=trim((string)($r->input('status')??''));$limit=(int)($r->input('limit')??50);$offset=(int)($r->input('offset')??0);return Response::json(['data'=>(new PppoeEnforcementAuditQuery($this->pdo))->list($t,$status!==''?$status:null,$limit,$offset)]);}
 public function summary(Request $r):Response{return Response::json(['data'=>(new PppoeEnforcementAuditQuery($this->pdo))->summary($this->tenant($r))]);}
 public function page(Request $r):Response{return Response::text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="stylesheet" href="/assets/css/app.css"><title>PPPoE Enforcement Audit</title><style>.audit-wrap{max-width:1100px;margin:auto;padding:16px}.audit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.audit-card{padding:14px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.audit-value{font-size:25px;font-weight:700}.audit-toolbar{display:grid;grid-template-columns:1fr auto;gap:10px;margin:14px 0}.audit-list{display:grid;gap:10px}.audit-row{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:14px}.status{display:inline-flex;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:700;text-transform:uppercase}.success{background:#dcfce7;color:#166534}.failed{background:#fee2e2;color:#991b1b}.mismatch{background:#ffedd5;color:#9a3412}.muted{color:#64748b;font-size:13px}.row-head{display:flex;justify-content:space-between;gap:10px}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-top:10px;font-size:13px}@media(max-width:640px){.audit-grid{grid-template-columns:1fr 1fr 1fr}.audit-toolbar{grid-template-columns:1fr}.meta{grid-template-columns:1fr}.audit-wrap{padding:10px}.audit-card{padding:11px}.audit-value{font-size:21px}}</style></head><body><main class="audit-wrap"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><h1 style="margin:.2rem 0">PPPoE Enforcement Audit</h1><div class="muted">MikroTik state verification history</div></div><a class="btn" href="/">Dashboard</a></div><section class="audit-grid" style="margin-top:14px"><div class="audit-card"><div class="muted">Success</div><div id="success" class="audit-value">—</div></div><div class="audit-card"><div class="muted">Failed</div><div id="failed" class="audit-value">—</div></div><div class="audit-card"><div class="muted">Mismatch</div><div id="mismatch" class="audit-value">—</div></div></section><div class="audit-toolbar"><select id="status" class="input"><option value="">All statuses</option><option value="success">Success</option><option value="failed">Failed</option><option value="mismatch">Mismatch</option></select><button class="btn" id="refresh">Refresh</button></div><section id="list" class="audit-list"><div class="audit-row muted">Loading…</div></section></main><script src="/assets/js/pppoe-enforcement-audit.js" defer></script></body></html>');}
}
