<?php

declare(strict_types=1);

namespace Ispluka\Controllers;
use Ispluka\Core\Auth\AuthManager;use Ispluka\Core\Auth\Password;use Ispluka\Core\Auth\RoleManager;use Ispluka\Core\Database\Database;use Ispluka\Core\Http\Request;use Ispluka\Core\Http\Response;use Ispluka\Core\Security\Csrf;use Throwable;
final class TenantController{
public function __construct(private readonly Database $database,private readonly AuthManager $auth,private readonly RoleManager $roles,private readonly Csrf $csrf){}
public function page():Response{$this->requireMasterAdmin();$tenants=$this->database->pdo()->query("SELECT t.id,t.name,t.code,t.status,t.created_at,(SELECT COUNT(*) FROM users u WHERE u.tenant_id=t.id AND u.deleted_at IS NULL) users_count,(SELECT COUNT(*) FROM customers c WHERE c.tenant_id=t.id AND c.deleted_at IS NULL) customers_count FROM tenants t WHERE t.deleted_at IS NULL ORDER BY t.id DESC")->fetchAll();$csrf=htmlspecialchars($this->csrf->token(),ENT_QUOTES,'UTF-8');$created=isset($_GET['created'])&&$_GET['created']==='1';$rows='';foreach($tenants as $t)$rows.='<tr><td>'.(int)$t['id'].'</td><td><strong>'.htmlspecialchars((string)$t['name']).'</strong><br><span class="muted">'.htmlspecialchars((string)$t['code']).'</span></td><td>'.htmlspecialchars((string)$t['status']).'</td><td>'.(int)$t['users_count'].'</td><td>'.(int)$t['customers_count'].'</td><td>'.htmlspecialchars((string)$t['created_at']).'</td></tr>';$notice=$created?'<div class="card" style="border-color:#86efac;background:#f0fdf4;color:#166534"><strong>Tenant and Admin created successfully.</strong></div>':'';return Response::text('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/css/app.css"><title>Tenants · ISPLUKA</title></head><body><main class="main"><div class="container">'.$notice.'<div class="page-title"><div><h1>Tenants / Admins</h1><p class="muted">Create an ISP tenant and its first Admin account.</p></div><a class="btn btn-secondary" href="/">Dashboard</a></div><section class="card stack"><form method="post" action="/admin/tenants" class="stack"><input type="hidden" name="_csrf" value="'.$csrf.'"><h2>New Tenant</h2><div class="form-grid"><div><label>ISP Name *</label><input name="name" required maxlength="160"></div><div><label>Tenant Code *</label><input name="code" required maxlength="50" pattern="[A-Za-z0-9_-]+"></div><div><label>Legal Name</label><input name="legal_name" maxlength="200"></div><div><label>Timezone</label><input name="timezone" value="Asia/Dhaka" maxlength="64"></div></div><h3>First Admin Account</h3><div class="form-grid"><div><label>Admin Name *</label><input name="admin_name" required maxlength="160"></div><div><label>Admin Email</label><input type="email" name="admin_email" maxlength="190"></div><div><label>Admin Phone</label><input name="admin_phone" maxlength="30"></div><div><label>Password *</label><input type="password" name="admin_password" required minlength="8"></div></div><button type="submit">Create Tenant + Admin</button></form></section><section class="card"><h2>Existing Tenants</h2><div class="table-wrap"><table><thead><tr><th>ID</th><th>Tenant</th><th>Status</th><th>Users</th><th>Customers</th><th>Created</th></tr></thead><tbody>'.$rows.'</tbody></table></div></section></div></main></body></html>');}
public function store(Request $request):Response{$this->requireMasterAdmin();$name=trim((string)$request->input('name',''));$code=strtolower(trim((string)$request->input('code','')));$legal=trim((string)$request->input('legal_name',''));$timezone=trim((string)$request->input('timezone','Asia/Dhaka'))?:'Asia/Dhaka';$adminName=trim((string)$request->input('admin_name',''));$email=trim((string)$request->input('admin_email',''));$phone=trim((string)$request->input('admin_phone',''));$password=(string)$request->input('admin_password','');if($name===''||$adminName===''||strlen($password)<8||!preg_match('/^[a-z0-9_-]{2,50}$/',$code))return Response::json(['error'=>['message'=>'Tenant name, valid code, admin name and password are required.']],422);$pdo=$this->database->pdo();try{$pdo->beginTransaction();$s=$pdo->prepare("INSERT INTO tenants(name,code,legal_name,timezone,currency,status) VALUES(:name,:code,:legal,:timezone,'BDT','trial') RETURNING id");$s->execute(['name'=>$name,'code'=>$code,'legal'=>$legal!==''?$legal:null,'timezone'=>$timezone]);$tenantId=(int)$s->fetchColumn();$this->roles->provisionTenantRoles($tenantId);$u=$pdo->prepare('INSERT INTO users(tenant_id,name,email,phone,password_hash) VALUES(:tenant_id,:name,:email,:phone,:hash) RETURNING id');$u->execute(['tenant_id'=>$tenantId,'name'=>$adminName,'email'=>$email!==''?$email:null,'phone'=>$phone!==''?$phone:null,'hash'=>Password::hash($password)]);$this->roles->assign((int)$u->fetchColumn(),'admin',$tenantId);$pdo->prepare("INSERT INTO tenant_subscriptions(tenant_id,plan_code,amount,starts_at,ends_at,status) VALUES(:tenant,'trial',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP+INTERVAL '30 days','trial')")->execute(['tenant'=>$tenantId]);$pdo->commit();return Response::redirect('/admin/tenants?created=1');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();return Response::json(['error'=>['message'=>$this->safeError($e)]],422);}}
private function requireMasterAdmin():void{$uid=$this->auth->userId();if(!$uid)throw new \RuntimeException('Authentication required.',401);$s=$this->database->pdo()->prepare("SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=:uid AND r.tenant_id IS NULL AND r.code='master_admin' LIMIT 1");$s->execute(['uid'=>$uid]);if($s->fetchColumn()===false)throw new \RuntimeException('Forbidden.',403);}
private function safeError(Throwable $e):string{$m=strtolower($e->getMessage());return str_contains($m,'duplicate')||str_contains($m,'unique')?'Tenant code or admin email already exists.':'Unable to create tenant. Please check the submitted data.';}}
